//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'accounts.dart';
export 'api_keys.dart';
export 'campaign_runs.dart';
export 'campaigns.dart';
export 'config.dart';
export 'email_logs.dart';
export 'folders.dart';
export 'newsletter_subscribers.dart';
export 'plans.dart';
export 'recipients.dart';
export 'subscriptions.dart';
export 'support_ticket_categories.dart';
export 'support_tickets.dart';
export 'template_categories.dart';
export 'template_keyword_map.dart';
export 'template_keywords.dart';
export 'templates.dart';
export 'user_notifications.dart';
export 'user_settings.dart';
export 'users.dart';

/// Date: 2025-08-08 19:06:35.390905
