//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Campaign Runs Table
class CampaignRunsTable extends SupabaseTable<CampaignRunsRow> {
  /// Table Name
  @override
  String get tableName => 'campaign_runs';

  /// Create a [CampaignRunsRow] from the [data] provided
  @override
  CampaignRunsRow createRow(Map<String, dynamic> data) =>
      CampaignRunsRow.fromJson(data);
}

/// Campaign Runs Row
class CampaignRunsRow extends SupabaseDataRow {
  /// Campaign Runs Row
  CampaignRunsRow({
    String? id,
    DateTime? createdAt,
    String? campaignId,
    String? uid,
    CampaignRunStatus? status,
    DateTime? endedAt,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (campaignId != null) 'campaign_id': supaSerialize(campaignId),
         if (uid != null) 'uid': supaSerialize(uid),
         if (status != null) 'status': supaSerialize(status),
         if (endedAt != null) 'ended_at': supaSerialize(endedAt),
       });

  /// Campaign Runs Row
  const CampaignRunsRow._(super.data);

  /// Create Campaign Runs Row from a [data] map
  factory CampaignRunsRow.fromJson(Map<String, dynamic> data) =>
      CampaignRunsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => CampaignRunsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Campaign Id field name
  static const String campaignIdField = 'campaign_id';

  /// Campaign Id
  String? get campaignId => getField<String>(campaignIdField);
  set campaignId(String? value) => setField<String>(campaignIdField, value);

  /// Uid field name
  static const String uidField = 'uid';

  /// Uid
  String get uid => getField<String>(uidField, defaultValue: 'auth.')!;
  set uid(String value) => setField<String>(uidField, value);

  /// Status field name
  static const String statusField = 'status';

  /// Status
  CampaignRunStatus? get status => getField<CampaignRunStatus>(
    statusField,
    enumValues: CampaignRunStatus.values,
  );
  set status(CampaignRunStatus? value) =>
      setField<CampaignRunStatus>(statusField, value);

  /// Ended At field name
  static const String endedAtField = 'ended_at';

  /// Ended At
  DateTime? get endedAt => getField<DateTime>(endedAtField);
  set endedAt(DateTime? value) => setField<DateTime>(endedAtField, value);

  /// Make a copy of the current [CampaignRunsRow]
  /// overriding the provided fields
  CampaignRunsRow copyWith({
    String? id,
    DateTime? createdAt,
    String? campaignId,
    String? uid,
    CampaignRunStatus? status,
    DateTime? endedAt,
  }) => CampaignRunsRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'campaign_id': supaSerialize(campaignId) ?? data['campaign_id'],
    'uid': supaSerialize(uid) ?? data['uid'],
    'status': supaSerialize(status) ?? data['status'],
    'ended_at': supaSerialize(endedAt) ?? data['ended_at'],
  });
}

/// Date: 2025-08-08 19:06:35.290725
