//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Recipients Table
class RecipientsTable extends SupabaseTable<RecipientsRow> {
  /// Table Name
  @override
  String get tableName => 'recipients';

  /// Create a [RecipientsRow] from the [data] provided
  @override
  RecipientsRow createRow(Map<String, dynamic> data) =>
      RecipientsRow.fromJson(data);
}

/// Recipients Row
class RecipientsRow extends SupabaseDataRow {
  /// Recipients Row
  RecipientsRow({
    String? id,
    String? uid,
    String? folderId,
    String? email,
    String? firstName,
    String? lastName,
    String? phone,
    String? company,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? customFields,
    DateTime? unsubscribedAt,
    String? name,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (uid != null) 'uid': supaSerialize(uid),
         if (folderId != null) 'folder_id': supaSerialize(folderId),
         if (email != null) 'email': supaSerialize(email),
         if (firstName != null) 'first_name': supaSerialize(firstName),
         if (lastName != null) 'last_name': supaSerialize(lastName),
         if (phone != null) 'phone': supaSerialize(phone),
         if (company != null) 'company': supaSerialize(company),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
         if (customFields != null) 'custom_fields': supaSerialize(customFields),
         if (unsubscribedAt != null)
           'unsubscribed_at': supaSerialize(unsubscribedAt),
         if (name != null) 'name': supaSerialize(name),
       });

  /// Recipients Row
  const RecipientsRow._(super.data);

  /// Create Recipients Row from a [data] map
  factory RecipientsRow.fromJson(Map<String, dynamic> data) =>
      RecipientsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => RecipientsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Uid field name
  static const String uidField = 'uid';

  /// Uid
  String get uid => getField<String>(uidField, defaultValue: 'auth.')!;
  set uid(String value) => setField<String>(uidField, value);

  /// Folder Id field name
  static const String folderIdField = 'folder_id';

  /// Folder Id
  String? get folderId => getField<String>(folderIdField);
  set folderId(String? value) => setField<String>(folderIdField, value);

  /// Email field name
  static const String emailField = 'email';

  /// Email
  String? get email => getField<String>(emailField);
  set email(String? value) => setField<String>(emailField, value);

  /// First Name field name
  static const String firstNameField = 'first_name';

  /// First Name
  String? get firstName => getField<String>(firstNameField);
  set firstName(String? value) => setField<String>(firstNameField, value);

  /// Last Name field name
  static const String lastNameField = 'last_name';

  /// Last Name
  String? get lastName => getField<String>(lastNameField);
  set lastName(String? value) => setField<String>(lastNameField, value);

  /// Phone field name
  static const String phoneField = 'phone';

  /// Phone
  String? get phone => getField<String>(phoneField);
  set phone(String? value) => setField<String>(phoneField, value);

  /// Company field name
  static const String companyField = 'company';

  /// Company
  String? get company => getField<String>(companyField);
  set company(String? value) => setField<String>(companyField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Custom Fields field name
  static const String customFieldsField = 'custom_fields';

  /// Custom Fields
  Map<String, dynamic>? get customFields =>
      getField<Map<String, dynamic>>(customFieldsField);
  set customFields(Map<String, dynamic>? value) =>
      setField<Map<String, dynamic>>(customFieldsField, value);

  /// Unsubscribed At field name
  static const String unsubscribedAtField = 'unsubscribed_at';

  /// Unsubscribed At
  DateTime? get unsubscribedAt => getField<DateTime>(unsubscribedAtField);
  set unsubscribedAt(DateTime? value) =>
      setField<DateTime>(unsubscribedAtField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String? get name => getField<String>(nameField);
  set name(String? value) => setField<String>(nameField, value);

  /// Make a copy of the current [RecipientsRow]
  /// overriding the provided fields
  RecipientsRow copyWith({
    String? id,
    String? uid,
    String? folderId,
    String? email,
    String? firstName,
    String? lastName,
    String? phone,
    String? company,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? customFields,
    DateTime? unsubscribedAt,
    String? name,
  }) => RecipientsRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'uid': supaSerialize(uid) ?? data['uid'],
    'folder_id': supaSerialize(folderId) ?? data['folder_id'],
    'email': supaSerialize(email) ?? data['email'],
    'first_name': supaSerialize(firstName) ?? data['first_name'],
    'last_name': supaSerialize(lastName) ?? data['last_name'],
    'phone': supaSerialize(phone) ?? data['phone'],
    'company': supaSerialize(company) ?? data['company'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
    'custom_fields': supaSerialize(customFields) ?? data['custom_fields'],
    'unsubscribed_at': supaSerialize(unsubscribedAt) ?? data['unsubscribed_at'],
    'name': supaSerialize(name) ?? data['name'],
  });
}

/// Date: 2025-08-08 19:06:35.327468
