//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Support Ticket Categories Table
class SupportTicketCategoriesTable
    extends SupabaseTable<SupportTicketCategoriesRow> {
  /// Table Name
  @override
  String get tableName => 'support_ticket_categories';

  /// Create a [SupportTicketCategoriesRow] from the [data] provided
  @override
  SupportTicketCategoriesRow createRow(Map<String, dynamic> data) =>
      SupportTicketCategoriesRow.fromJson(data);
}

/// Support Ticket Categories Row
class SupportTicketCategoriesRow extends SupabaseDataRow {
  /// Support Ticket Categories Row
  SupportTicketCategoriesRow({required String name, String? id})
    : super({
        'name': supaSerialize(name),
        if (id != null) 'id': supaSerialize(id),
      });

  /// Support Ticket Categories Row
  const SupportTicketCategoriesRow._(super.data);

  /// Create Support Ticket Categories Row from a [data] map
  factory SupportTicketCategoriesRow.fromJson(Map<String, dynamic> data) =>
      SupportTicketCategoriesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => SupportTicketCategoriesTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField)!;
  set name(String value) => setField<String>(nameField, value);

  /// Make a copy of the current [SupportTicketCategoriesRow]
  /// overriding the provided fields
  SupportTicketCategoriesRow copyWith({String? name, String? id}) =>
      SupportTicketCategoriesRow.fromJson({
        'name': supaSerialize(name) ?? data['name'],
        'id': supaSerialize(id) ?? data['id'],
      });
}

/// Date: 2025-08-08 19:06:35.339597
