//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Template Keyword Map Table
class TemplateKeywordMapTable extends SupabaseTable<TemplateKeywordMapRow> {
  /// Table Name
  @override
  String get tableName => 'template_keyword_map';

  /// Create a [TemplateKeywordMapRow] from the [data] provided
  @override
  TemplateKeywordMapRow createRow(Map<String, dynamic> data) =>
      TemplateKeywordMapRow.fromJson(data);
}

/// Template Keyword Map Row
class TemplateKeywordMapRow extends SupabaseDataRow {
  /// Template Keyword Map Row
  TemplateKeywordMapRow({required String templateId, required String keywordId})
    : super({
        'template_id': supaSerialize(templateId),
        'keyword_id': supaSerialize(keywordId),
      });

  /// Template Keyword Map Row
  const TemplateKeywordMapRow._(super.data);

  /// Create Template Keyword Map Row from a [data] map
  factory TemplateKeywordMapRow.fromJson(Map<String, dynamic> data) =>
      TemplateKeywordMapRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => TemplateKeywordMapTable();

  /// Template Id field name
  static const String templateIdField = 'template_id';

  /// Template Id
  String get templateId => getField<String>(templateIdField)!;
  set templateId(String value) => setField<String>(templateIdField, value);

  /// Keyword Id field name
  static const String keywordIdField = 'keyword_id';

  /// Keyword Id
  String get keywordId => getField<String>(keywordIdField)!;
  set keywordId(String value) => setField<String>(keywordIdField, value);

  /// Make a copy of the current [TemplateKeywordMapRow]
  /// overriding the provided fields
  TemplateKeywordMapRow copyWith({String? templateId, String? keywordId}) =>
      TemplateKeywordMapRow.fromJson({
        'template_id': supaSerialize(templateId) ?? data['template_id'],
        'keyword_id': supaSerialize(keywordId) ?? data['keyword_id'],
      });
}

/// Date: 2025-08-08 19:06:35.357183
