//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Template Categories Table
class TemplateCategoriesTable extends SupabaseTable<TemplateCategoriesRow> {
  /// Table Name
  @override
  String get tableName => 'template_categories';

  /// Create a [TemplateCategoriesRow] from the [data] provided
  @override
  TemplateCategoriesRow createRow(Map<String, dynamic> data) =>
      TemplateCategoriesRow.fromJson(data);
}

/// Template Categories Row
class TemplateCategoriesRow extends SupabaseDataRow {
  /// Template Categories Row
  TemplateCategoriesRow({
    required String name,
    String? id,
    String? description,
    DateTime? createdAt,
  }) : super({
         'name': supaSerialize(name),
         if (id != null) 'id': supaSerialize(id),
         if (description != null) 'description': supaSerialize(description),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
       });

  /// Template Categories Row
  const TemplateCategoriesRow._(super.data);

  /// Create Template Categories Row from a [data] map
  factory TemplateCategoriesRow.fromJson(Map<String, dynamic> data) =>
      TemplateCategoriesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => TemplateCategoriesTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Name field name
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField)!;
  set name(String value) => setField<String>(nameField, value);

  /// Description field name
  static const String descriptionField = 'description';

  /// Description
  String? get description => getField<String>(descriptionField);
  set description(String? value) => setField<String>(descriptionField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Make a copy of the current [TemplateCategoriesRow]
  /// overriding the provided fields
  TemplateCategoriesRow copyWith({
    String? name,
    String? id,
    String? description,
    DateTime? createdAt,
  }) => TemplateCategoriesRow.fromJson({
    'name': supaSerialize(name) ?? data['name'],
    'id': supaSerialize(id) ?? data['id'],
    'description': supaSerialize(description) ?? data['description'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
  });
}

/// Date: 2025-08-08 19:06:35.350135
