//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Template Keywords Table
class TemplateKeywordsTable extends SupabaseTable<TemplateKeywordsRow> {
  /// Table Name
  @override
  String get tableName => 'template_keywords';

  /// Create a [TemplateKeywordsRow] from the [data] provided
  @override
  TemplateKeywordsRow createRow(Map<String, dynamic> data) =>
      TemplateKeywordsRow.fromJson(data);
}

/// Template Keywords Row
class TemplateKeywordsRow extends SupabaseDataRow {
  /// Template Keywords Row
  TemplateKeywordsRow({required String keyword, String? id})
    : super({
        'keyword': supaSerialize(keyword),
        if (id != null) 'id': supaSerialize(id),
      });

  /// Template Keywords Row
  const TemplateKeywordsRow._(super.data);

  /// Create Template Keywords Row from a [data] map
  factory TemplateKeywordsRow.fromJson(Map<String, dynamic> data) =>
      TemplateKeywordsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => TemplateKeywordsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Keyword field name
  static const String keywordField = 'keyword';

  /// Keyword
  String get keyword => getField<String>(keywordField)!;
  set keyword(String value) => setField<String>(keywordField, value);

  /// Make a copy of the current [TemplateKeywordsRow]
  /// overriding the provided fields
  TemplateKeywordsRow copyWith({String? keyword, String? id}) =>
      TemplateKeywordsRow.fromJson({
        'keyword': supaSerialize(keyword) ?? data['keyword'],
        'id': supaSerialize(id) ?? data['id'],
      });
}

/// Date: 2025-08-08 19:06:35.362704
