//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Notifications Table
class UserNotificationsTable extends SupabaseTable<UserNotificationsRow> {
  /// Table Name
  @override
  String get tableName => 'user_notifications';

  /// Create a [UserNotificationsRow] from the [data] provided
  @override
  UserNotificationsRow createRow(Map<String, dynamic> data) =>
      UserNotificationsRow.fromJson(data);
}

/// User Notifications Row
class UserNotificationsRow extends SupabaseDataRow {
  /// User Notifications Row
  UserNotificationsRow({
    String? id,
    String? uid,
    String? title,
    String? message,
    String? link,
    bool? isRead,
    DateTime? createdAt,
    String? type,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (uid != null) 'uid': supaSerialize(uid),
         if (title != null) 'title': supaSerialize(title),
         if (message != null) 'message': supaSerialize(message),
         if (link != null) 'link': supaSerialize(link),
         if (isRead != null) 'is_read': supaSerialize(isRead),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (type != null) 'type': supaSerialize(type),
       });

  /// User Notifications Row
  const UserNotificationsRow._(super.data);

  /// Create User Notifications Row from a [data] map
  factory UserNotificationsRow.fromJson(Map<String, dynamic> data) =>
      UserNotificationsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserNotificationsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Uid field name
  static const String uidField = 'uid';

  /// Uid
  String get uid => getField<String>(uidField, defaultValue: 'auth.')!;
  set uid(String value) => setField<String>(uidField, value);

  /// Title field name
  static const String titleField = 'title';

  /// Title
  String? get title => getField<String>(titleField);
  set title(String? value) => setField<String>(titleField, value);

  /// Message field name
  static const String messageField = 'message';

  /// Message
  String? get message => getField<String>(messageField);
  set message(String? value) => setField<String>(messageField, value);

  /// Link field name
  static const String linkField = 'link';

  /// Link
  String? get link => getField<String>(linkField);
  set link(String? value) => setField<String>(linkField, value);

  /// Is Read field name
  static const String isReadField = 'is_read';

  /// Is Read
  bool? get isRead => getField<bool>(isReadField);
  set isRead(bool? value) => setField<bool>(isReadField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime? get createdAt => getField<DateTime>(createdAtField);
  set createdAt(DateTime? value) => setField<DateTime>(createdAtField, value);

  /// Type field name
  static const String typeField = 'type';

  /// Type
  String? get type => getField<String>(typeField);
  set type(String? value) => setField<String>(typeField, value);

  /// Make a copy of the current [UserNotificationsRow]
  /// overriding the provided fields
  UserNotificationsRow copyWith({
    String? id,
    String? uid,
    String? title,
    String? message,
    String? link,
    bool? isRead,
    DateTime? createdAt,
    String? type,
  }) => UserNotificationsRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'uid': supaSerialize(uid) ?? data['uid'],
    'title': supaSerialize(title) ?? data['title'],
    'message': supaSerialize(message) ?? data['message'],
    'link': supaSerialize(link) ?? data['link'],
    'is_read': supaSerialize(isRead) ?? data['is_read'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'type': supaSerialize(type) ?? data['type'],
  });
}

/// Date: 2025-08-08 19:06:35.372779
