//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// User Settings Table
class UserSettingsTable extends SupabaseTable<UserSettingsRow> {
  /// Table Name
  @override
  String get tableName => 'user_settings';

  /// Create a [UserSettingsRow] from the [data] provided
  @override
  UserSettingsRow createRow(Map<String, dynamic> data) =>
      UserSettingsRow.fromJson(data);
}

/// User Settings Row
class UserSettingsRow extends SupabaseDataRow {
  /// User Settings Row
  UserSettingsRow({
    String? id,
    String? defaultTimezone,
    String? fromName,
    String? uid,
    String? emailSignature,
    String? smtpLogsRetention,
    String? replyToEmail,
  }) : super({
         if (id != null) 'id': supaSerialize(id),
         if (defaultTimezone != null)
           'default_timezone': supaSerialize(defaultTimezone),
         if (fromName != null) 'from_name': supaSerialize(fromName),
         if (uid != null) 'uid': supaSerialize(uid),
         if (emailSignature != null)
           'email_signature': supaSerialize(emailSignature),
         if (smtpLogsRetention != null)
           'smtp_logs_retention': supaSerialize(smtpLogsRetention),
         if (replyToEmail != null)
           'reply_to_email': supaSerialize(replyToEmail),
       });

  /// User Settings Row
  const UserSettingsRow._(super.data);

  /// Create User Settings Row from a [data] map
  factory UserSettingsRow.fromJson(Map<String, dynamic> data) =>
      UserSettingsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UserSettingsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField, defaultValue: '')!;
  set id(String value) => setField<String>(idField, value);

  /// Default Timezone field name
  static const String defaultTimezoneField = 'default_timezone';

  /// Default Timezone
  String? get defaultTimezone => getField<String>(defaultTimezoneField);
  set defaultTimezone(String? value) =>
      setField<String>(defaultTimezoneField, value);

  /// From Name field name
  static const String fromNameField = 'from_name';

  /// From Name
  String? get fromName => getField<String>(fromNameField);
  set fromName(String? value) => setField<String>(fromNameField, value);

  /// Uid field name
  static const String uidField = 'uid';

  /// Uid
  String get uid => getField<String>(uidField, defaultValue: 'auth.')!;
  set uid(String value) => setField<String>(uidField, value);

  /// Email Signature field name
  static const String emailSignatureField = 'email_signature';

  /// Email Signature
  String? get emailSignature => getField<String>(emailSignatureField);
  set emailSignature(String? value) =>
      setField<String>(emailSignatureField, value);

  /// Smtp Logs Retention field name
  static const String smtpLogsRetentionField = 'smtp_logs_retention';

  /// Smtp Logs Retention
  String? get smtpLogsRetention => getField<String>(smtpLogsRetentionField);
  set smtpLogsRetention(String? value) =>
      setField<String>(smtpLogsRetentionField, value);

  /// Reply To Email field name
  static const String replyToEmailField = 'reply_to_email';

  /// Reply To Email
  String? get replyToEmail => getField<String>(replyToEmailField);
  set replyToEmail(String? value) => setField<String>(replyToEmailField, value);

  /// Make a copy of the current [UserSettingsRow]
  /// overriding the provided fields
  UserSettingsRow copyWith({
    String? id,
    String? defaultTimezone,
    String? fromName,
    String? uid,
    String? emailSignature,
    String? smtpLogsRetention,
    String? replyToEmail,
  }) => UserSettingsRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'default_timezone':
        supaSerialize(defaultTimezone) ?? data['default_timezone'],
    'from_name': supaSerialize(fromName) ?? data['from_name'],
    'uid': supaSerialize(uid) ?? data['uid'],
    'email_signature': supaSerialize(emailSignature) ?? data['email_signature'],
    'smtp_logs_retention':
        supaSerialize(smtpLogsRetention) ?? data['smtp_logs_retention'],
    'reply_to_email': supaSerialize(replyToEmail) ?? data['reply_to_email'],
  });
}

/// Date: 2025-08-08 19:06:35.379219
