//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Campaign Status enum
enum CampaignStatus {
  /// idle
  idle,

  /// running
  running,

  /// finished
  finished,

  /// paused
  paused,

  /// stopped
  stopped,

  /// scheduled
  scheduled,
}

/// Date: 2025-08-08 19:06:35.033674
