//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Email Log Status enum
enum EmailLogStatus {
  /// pending
  pending,

  /// sent
  sent,

  /// failed
  failed,

  /// paused
  paused,

  /// stopped
  stopped,

  /// deferred
  deferred,
}

/// Date: 2025-08-08 19:06:35.035658
