//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Subscription Status enum
enum SubscriptionStatus {
  /// authenticated
  authenticated,

  /// paused
  paused,

  /// resumed
  resumed,

  /// active
  active,

  /// pending
  pending,

  /// halted
  halted,

  /// charged
  charged,

  /// cancelled
  cancelled,

  /// completed
  completed,

  /// updated
  updated,

  /// created
  created,
}

/// Date: 2025-08-08 19:06:35.039661
