//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Support Ticket Category enum
enum SupportTicketCategory {
  /// Recipient Management
  RecipientManagement,
  /// Campaign Management
  CampaignManagement,
  /// App Performance _ Bugs
  AppPerformanceBugs,
  /// Bounce & Delivery Issues
  BounceDeliveryIssues,
  /// Email Templates
  EmailTemplates,
  /// Feature Request
  FeatureRequest,
  /// Analytics & Tracking
  AnalyticsTracking,
  /// Billing & Subscription
  BillingSubscription,
  /// Login & Authentication
  LoginAuthentication,
  /// Email Sending Issues
  EmailSendingIssues,
}

/// Date: 2025-08-08 19:06:35.046241
