//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Template Use Case enum
enum TemplateUseCase {
  /// promotion
  promotion,

  /// announcement
  announcement,

  /// transactional
  transactional,

  /// welcome
  welcome,

  /// survey
  survey,
}

/// Date: 2025-08-08 19:06:35.056703
