//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Ticket Status enum
enum TicketStatus {
  /// open
  open,

  /// in_progress
  in_progress,

  /// closed
  closed,

  /// resolved
  resolved,

  /// reopened
  reopened,
}

/// Date: 2025-08-08 19:06:35.070333
