//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Ticket Priority enum
enum TicketPriority {
  /// low
  low,

  /// medium
  medium,

  /// high
  high,

  /// urgent
  urgent,
}

/// Date: 2025-08-08 19:06:35.059695
